---
dontChroot: false
timeout: 999
script:
    # --- Limpieza y Post-instalación ---
    - "sed -i '/luminauser ALL=(ALL) NOPASSWD: ALL/d' /etc/sudoers"
    - "rm -f /etc/sudoers.d/10-installer"
    - "pacman -U --noconfirm /usr/share/lumina/yay-bin-*.pkg.tar.zst"
    - "pacman -U --noconfirm /usr/share/lumina/libpamac-aur-*.pkg.tar.zst /usr/share/lumina/pamac-aur-*.pkg.tar.zst"
    - "rm -rf /etc/systemd/system/getty@tty1.service.d"
    - "rm -f /usr/share/lumina/*.pkg.tar.zst"
    - "rm -rf /etc/calamares"
    - "rm -rf /var/log/calamares"
    - "pacman -R --noconfirm xorg-server || true"
    - "pacman -R --noconfirm xorg-xinit || true"
    - "pacman -R --noconfirm openbox || true"
    - "pacman -R --noconfirm terminus-font || true"
    - "pacman -R --noconfirm calamares || true"
    - "pacman -R --noconfirm kpmcore || true"
    - "pacman -R --noconfirm libpwquality || true"
    - "pacman -R --noconfirm qt6-base || true"
    - "pacman -R --noconfirm qt6-declarative || true"
    - "pacman -R --noconfirm qt6-svg || true"
    - "pacman -R --noconfirm yaml-cpp || true"
    # --- Exterminar fantasmas del Archiso e inicializar Keyring ---
    # 1. Borramos los archivos existentes para evitar conflictos
    - "rm -f /etc/systemd/system/pacman-init.service"
    - "rm -f /etc/systemd/system/etc-pacman.d-gnupg.mount"

    # 2. Ahora sí enmascaramos (aquí es donde systemctl crea el enlace a /dev/null)
    - "systemctl mask pacman-init.service"
    - "systemctl mask etc-pacman.d-gnupg.mount"

    # 3. Limpieza y preparación del Keyring
    - "rm -rf /etc/pacman.d/gnupg"
    - "mkdir -p /etc/pacman.d/gnupg"
    - "chmod 700 /etc/pacman.d/gnupg"
    - "pacman-key --init"
    - "pacman-key --populate archlinux lumina"
    - "pacman-key --lsign-key 093B74E82FCA45014329D8B1FE2080D27FBE66D8"
